adjective1=input("enter a adjective(description)")
noun1=input("enter a nonun (person,place,thing)")
adjective2=input("enter a adjective(description)")
verb1=input("enter a verb with 'ing ")
adjective3=input("enter a adjective(description)")
print(f"today I want to a {adjective1} zoo")
print(f"In an exhibit, i saw {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"i was {adjective3}")
